porcupine:
  keyword_path: /home/polygon-beater-studio/porcupine-env-3.10/lib/python3.10/site-packages/pvporcupine/resources/keyword_files/linux/porcupine_linux.ppn
  access_key: 
tts:
  model_name: tts_models/cs/cv/vits
  language: cs
whisper:
  path: /home/polygon-beater-studio/whisper.cpp/build/bin/main
  model: /home/polygon-beater-studio/whisper.cpp/models/ggml-medium.bin
llama:
  path: /home/polygon-beater-studio/llama.cpp/bin/llama-cli
  model: /home/polygon-beater-studio/llama.cpp/models/mixtral-7b-instruct-v0.2.Q4_K_M.gguf
  max_tokens: 512
audio:
  recording_file: command.wav
  rate: 16000
  record_duration: 5
  vad_aggressiveness: 3
  vad_frame_duration: 30
  silence_duration: 1000
  max_record_duration: 10
